apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dataalchemystacks.dataalchemy.io
spec:
  group: dataalchemy.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                projectName: {type: string}
                credentialsSecret: {type: string, default: "data-alchemy-secrets"}
                storage:
                  type: object
                  properties:
                    replicas: {type: integer, default: 1}
                    dataPath: {type: string}
                cache:
                  type: object
                  properties:
                    replicas: {type: integer, default: 1}
                compute:
                  type: object
                  properties:
                    spark:
                      type: object
                      properties:
                        image: {type: string, default: "data-alchemy:latest"}
                serviceType: {type: string, default: "ClusterIP"}
  scope: Namespaced
  names:
    plural: dataalchemystacks
    singular: dataalchemystack
    kind: DataAlchemyStack
    shortNames:
      - das
---
