apiVersion: dataalchemy.io/v1alpha1
kind: DataAlchemyStack
metadata:
  name: dataalchemy
spec:
  projectName: "DataAlchemy"
  credentialsSecret: "dataalchemy-secret"
  storage:
    replicas: 1
    dataPath: "/data"  # k3d volume mount path (maps to host $PROJECT_ROOT/data)
  cache:
    replicas: 1
  compute:
    spark:
      image: "data-processor:latest"
  # Use NodePort for k3d (LoadBalancer doesn't work in k3d)
  serviceType: "NodePort"
