apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: spark-cluster
servers: 1
agents: 2
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8888:8888 # Spark UI
    nodeFilters:
      - server:0
volumes:
  - volume: C:\Users\Administrator\work\LoRA:/app/data # Mount local workspace to /app/data in container
    nodeFilters:
      - server:0
      - agent:*
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
  kubeconfig:
    updateDefaultKubeconfig: true
    switchContext: true
