apiVersion: v1
kind: ServiceAccount
metadata:
  name: dataalchemy-operator-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataalchemy-operator-role
rules:
  - apiGroups: ["dataalchemy.io"]
    resources: ["dataalchemystacks", "dataalchemystacks/status"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["services", "pods", "configmaps", "secrets", "endpoints"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dataalchemy-operator-binding
subjects:
  - kind: ServiceAccount
    name: dataalchemy-operator-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: dataalchemy-operator-role
  apiGroup: rbac.authorization.k8s.io

