apiVersion: batch/v1
kind: Job
metadata:
  name: spark-data-cleaner
spec:
  template:
    spec:
      serviceAccountName: spark
      containers:
      - name: spark-driver
        image: data-processor:latest
        imagePullPolicy: Never
        env:
        - name: SPARK_MASTER
          value: "k8s://https://kubernetes.default.svc"
        - name: SPARK_IMAGE
          value: "data-processor:latest"
        - name: REDIS_URL
          value: "redis://test-stack-redis:6379"
        - name: S3_ENDPOINT
          value: "http://test-stack-minio:9000"
        - name: S3_BUCKET
          value: "lora-data"
        - name: PYTHONPATH
          value: "/app"
        command: ["python", "main.py"]
        args: ["--input", "/app/data/raw", "--output", "/app/data"]
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      restartPolicy: Never
      volumes:
      - name: data-volume
        hostPath:
          path: /run/desktop/mnt/host/c/Users/Administrator/work/LoRA/data
          type: Directory
  backoffLimit: 0
