apiVersion: batch/v1
kind: Job
metadata:
  name: spark-data-cleaner
spec:
  template:
    spec:
      serviceAccountName: spark
      containers:
      - name: spark-driver
        image: data-processor:latest
        imagePullPolicy: Never
        env:
        - name: SPARK_MASTER
          value: "local[*]"
        - name: SPARK_IMAGE
          value: "data-processor:latest"
        - name: PYTHONPATH
          value: "/app"
        # S3 Credentials for MinIO
        - name: AWS_ACCESS_KEY_ID
          value: "minioadmin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "minioadmin"
        - name: S3_ENDPOINT
          value: "http://minio:9000"
        command: ["python", "main.py"]
        # Use S3 paths
        args: ["--input", "s3a://lora-data/raw", "--output", "s3a://lora-data/processed"]
      restartPolicy: Never
  backoffLimit: 0


