apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
  namespace: {{ .Values.global.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: minio.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dataalchemy-minio
                port:
                  number: 9000
    - host: minio-console.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dataalchemy-minio
                port:
                  number: 9001
