{{- if .Values.operator.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dataalchemy-operator-sa
  namespace: {{ .Values.global.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataalchemy-operator-role
rules:
  - apiGroups: ["dataalchemy.io"]
    resources: ["dataalchemystacks", "dataalchemystacks/status"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["services", "pods", "configmaps", "secrets", "endpoints", "events"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dataalchemy-operator-binding
subjects:
  - kind: ServiceAccount
    name: dataalchemy-operator-sa
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: dataalchemy-operator-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataalchemy-operator
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "data-alchemy.labels" . | nindent 4 }}
    app: dataalchemy-operator
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      {{- include "data-alchemy.selectorLabels" . | nindent 6 }}
      app: dataalchemy-operator
  template:
    metadata:
      labels:
        {{- include "data-alchemy.selectorLabels" . | nindent 8 }}
        app: dataalchemy-operator
    spec:
      serviceAccountName: dataalchemy-operator-sa
      containers:
      - name: operator
        image: {{ .Values.images.operator }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        env:
        - name: DATAALCHEMY_DATA_PATH
          value: {{ .Values.operator.hostDataPath | quote }}
        volumeMounts:
        - name: templates
          mountPath: /app/deploy/operator/templates
      volumes:
      - name: templates
        configMap:
          name: dataalchemy-operator-templates
---
apiVersion: dataalchemy.io/v1alpha1
kind: DataAlchemyStack
metadata:
  name: dataalchemy
  namespace: {{ .Values.global.namespace }}
spec:
  projectName: "Default"
  credentialsSecret: "data-alchemy-secrets"
  storage:
    replicas: 1
    dataPath: {{ .Values.operator.hostDataPath | quote }}
    s3Bucket: {{ .Values.config.s3Bucket | quote }}
  compute:
    spark:
      image: {{ .Values.images.core | quote }}
{{- end }}
