apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-alchemy-sa
  namespace: {{ .Values.global.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: data-alchemy-role
  namespace: {{ .Values.global.namespace }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["*"]
- apiGroups: ["dataalchemy.io"]
  resources: ["dataalchemystacks"]
  verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: data-alchemy-rolebinding
  namespace: {{ .Values.global.namespace }}
subjects:
- kind: ServiceAccount
  name: data-alchemy-sa
  namespace: {{ .Values.global.namespace }}
roleRef:
  kind: Role
  name: data-alchemy-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: {{ .Values.global.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: {{ .Values.global.namespace }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch", "create", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-rolebinding
  namespace: {{ .Values.global.namespace }}
subjects:
- kind: ServiceAccount
  name: spark
  namespace: {{ .Values.global.namespace }}
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
