apiVersion: v1
kind: Secret
metadata:
  name: data-alchemy-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.credentials.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.credentials.awsSecretAccessKey | quote }}
  DEEPSEEK_API_KEY: {{ .Values.credentials.deepseekApiKey | quote }}
  DEEPSEEK_BASE_URL: {{ .Values.credentials.deepseekBaseUrl | quote }}
